language: shell
os: windows
sudo: required
before_install:
  - rm -r -f /c/Python27
  - powershell -Command "Set-ExecutionPolicy RemoteSigned -scope CurrentUser"
  - powershell -Command "Invoke-Expression (New-Object System.Net.WebClient).DownloadString('https://get.scoop.sh')"
  - scoop help
  - scoop install python
  - python -V

env: PATH=/c/Users/travis/scoop/apps/python/current:/c/Users/travis/scoop/apps/python/current/Scripts:/c/Users/travis/scoop/apps/python/current/Tools/Scripts:/c/Users/travis/scoop/shims:/c/Users/travis/scoop:$PATH
install:
  - python -m pip install --upgrade pip
  - pip install --upgrade pip
  - export TZ='Asia/Shanghai'
  - pip install -r requirements.txt
  - pip install pyinstaller
script:
  - pyinstaller -F gui.py --hidden-import ffpyplayer.threading  --hidden-import ffpyplayer.player.queue --hidden-import ffpyplayer.player.frame_queue --hidden-import ffpyplayer.player.decoder --hidden-import ffpyplayer.player.clock --hidden-import ffpyplayer.player.core
  - ls dist
deploy:
  provider: releases
  skip_cleanup: true
  file: "$TRAVIS_BUILD_DIR/dist/gui.exe"
  api_key: ${GITHUB_TOKEN}
  # user: ${GITHUBUSERNAME}
  # password: ${GITHUBPASSWORD}
  on:
    tags: true #发布  tag版 时才进行发包